"""
OCR Pipeline - PaddleOCR text extraction + HaS NER sensitive entity detection.

Facade module: the implementation now lives in seam-split siblings —
ocr_tuning (tuning constants + semantic vocabulary), ocr_cache (caches,
in-flight dedupe registries, stage metrics), ocr_image_prep (image
preparation + blank-page detection), ocr_paddle_extract (PaddleOCR-VL /
PP-StructureV3 extraction), ocr_block_merge (block merging),
ocr_table_semantics (HTML table expansion +
structural recall), ocr_visual_lines (visual-line reconstruction),
has_text_analysis (HaS NER text analysis) and ocr_entity_match
(entity-to-OCR matching).

This module stays the single public import surface: callers and tests keep
importing — and monkeypatching — app.services.vision.ocr_pipeline.
"""
from __future__ import annotations

import asyncio
import hashlib
import html
import io
import logging
import threading
import time
from collections import OrderedDict
from difflib import SequenceMatcher
from html.parser import HTMLParser
from typing import Any

import numpy as np
from PIL import Image, ImageOps

from app.core.config import settings
from app.core.visual_feature_categories import VISUAL_ONLY_ENTITY_TYPES
from app.models.type_mapping import TYPE_CN_TO_ID, TYPE_ID_TO_CN, has_query_labels_for
from app.services.ocr_has_vision_service import OCRTextBlock, SensitiveRegion
from app.services.vision.has_text_analysis import (
    run_has_text_analysis,
)
from app.services.vision.has_text_payload import (
    DEFAULT_HAS_TEXT_TYPE_IDS,
    _build_has_text_payload,
    _build_has_text_type_names,
    _canonical_image_text_type,
    _compact_text,
    _filter_blocks_for_has_text,
)
from app.services.vision.ocr_block_merge import (
    _is_coarse_markup_block,
    _merge_ocr_blocks,
)
from app.services.vision.ocr_cache import (
    _HAS_TEXT_NER_INFLIGHT,
    _HAS_TEXT_NER_INFLIGHT_LOOP,
    _OCR_TEXT_BLOCK_CACHE,
    _OCR_TEXT_BLOCK_CACHE_LOCK,
    _OCR_TEXT_BLOCK_INFLIGHT,
    _OCR_TEXT_BLOCK_INFLIGHT_LOCK,
    _add_has_text_duration,
    _begin_has_text_ner_inflight,
    _begin_ocr_output_inflight,
    _clone_ocr_output,
    _clone_sensitive_region,
    _clone_text_block,
    _copy_has_text_ner_result,
    _finish_has_text_ner_inflight,
    _finish_ocr_output_inflight,
    _get_cached_has_text_ner,
    _get_cached_ocr_output,
    _has_recent_negative_health,
    _has_text_ner_inflight_key,
    _image_png_bytes,
    _ocr_cache_enabled,
    _ocr_cache_key,
    _ocr_service_cache_identity,
    _OcrOutputInflight,
    _record_has_text_metric,
    _record_ocr_cache_stage,
    _record_ocr_stage_duration,
    _set_cached_ocr_output,
    _wait_for_ocr_output_inflight,
)
from app.services.vision.ocr_entity_match import (
    _AMOUNT_UNIT_SUFFIX_CHARS,
    _HAS_ENTITY_TYPE_MAPPING,
    DOCUMENT_TITLE_SUFFIXES,
    _char_visual_units,
    _char_word_class,
    _dedupe_ocr_regions,
    _entity_char_box_x_span,
    _entity_type_from_block_context,
    _extend_amount_pair_for_visual_match,
    _extend_entity_for_visual_match,
    _is_isolated_token_occurrence,
    _is_low_signal_vision_entity,
    _is_same_amount_value_block,
    _is_strict_match_entity,
    _iter_percent_value_tokens,
    _narrow_charsless_block_to_lines,
    _regions_overlap,
    _visual_match_span_for_entity,
    _visual_match_text_for_entity,
    match_entities_to_ocr,
)
from app.services.vision.ocr_image_prep import (
    _is_effectively_blank_page,
    prepare_image,
)
from app.services.vision.ocr_paddle_extract import (
    _has_coarse_markup_blocks,
    _has_coarse_multiline_blocks,
    _looks_like_table,
    _ocr_items_to_blocks,
    _run_ocr_service,
    _run_structure_service_with_visuals,
    _should_run_structure_fallback,
    run_paddle_ocr,
)
from app.services.vision.ocr_table_semantics import (
    _FIELD_LABEL_COLON_CHARS,
    DOCUMENT_NUMBER_FIELD_LABEL_TERMS,
    _amount_digit_count,
    _amount_digit_signature,
    _amount_header_column_spans,
    _amount_value_signature,
    _amount_values_from_header_spans,
    _amount_values_from_table_placements,
    _block_search_text,
    _compact_amount_candidate,
    _html_to_plain_text,
    _is_amount_column_cell,
    _is_amount_format_text,
    _is_amount_header_label,
    _is_document_number_field_label,
    _is_document_number_format_text,
    _is_standalone_amount_ocr_block,
    _merge_form_field_document_entities,
    _merge_table_amount_entities,
    _parse_table_placements,
    _split_field_label_value,
    expand_table_blocks,
    extract_table_cells,
    recall_form_field_document_numbers,
    recall_table_amount_entities,
)
from app.services.vision.ocr_tuning import (
    _AMOUNT_FORMAT_ALLOWED_CHARS,
    _AMOUNT_PAIR_LOOKBACK_CHARS,
    _AMOUNT_PAIR_MAX_LOWER_TAIL_UNITS,
    _AMOUNT_PAIR_NO_LOWER_MARKER_UNITS,
    _AMOUNT_TRAILING_ZEROS_MIN_DIGITS,
    _BLANK_PAGE_DARK_PIXEL_MAX,
    _BLANK_PAGE_DARK_RATIO_MAX,
    _BLANK_PAGE_INK_PIXEL_MAX,
    _BLANK_PAGE_INK_RATIO_MAX,
    _BLANK_PAGE_MIN_HEIGHT_PX,
    _BLANK_PAGE_MIN_WIDTH_PX,
    _BLANK_PAGE_THUMBNAIL_PX,
    _BRIDGE_COMBINED_MAX_LEN,
    _BRIDGE_LEFT_MAX_LEN,
    _BRIDGE_LEFT_MIN_CJK,
    _BRIDGE_LEFT_MIN_LEN,
    _BRIDGE_PAYLOAD_MAX_CHARS,
    _BRIDGE_RIGHT_MAX_LEN,
    _BRIDGE_RIGHT_MIN_CJK,
    _BRIDGE_RIGHT_MIN_LEN,
    _CHAR_UNIT_ALNUM,
    _CHAR_UNIT_CJK,
    _CHAR_UNIT_MIN_TOTAL,
    _CHAR_UNIT_OTHER,
    _CHAR_UNIT_PUNCT,
    _CHAR_UNIT_SPACE,
    _COARSE_MULTILINE_HEIGHT_MULT,
    _COARSE_MULTILINE_MIN_COMPACT_LEN,
    _DEFAULT_OCR_ITEM_CONFIDENCE,
    _FUZZY_MATCH_BLOCK_LEN_FLOOR,
    _FUZZY_MATCH_BLOCK_LEN_MULT,
    _FUZZY_MATCH_CONFIDENCE,
    _FUZZY_MATCH_MIN_ENTITY_LEN,
    _FUZZY_MATCH_RATIO,
    _HAS_NEGATIVE_HEALTH_TTL_SEC,
    _MERGE_DUPLICATE_IOU,
    _MERGE_OVERLAP_IOU,
    _NER_DEFAULT_MIN_LEN,
    _NER_MIN_LEN_BY_TYPE,
    _PAREN_CLOSE_CHARS,
    _PAREN_OPEN_CHARS,
    _PROPERTY_TITLE_TAIL_LOOKAHEAD_CHARS,
    _RECONSTRUCT_TALL_ASPECT_MULT,
    _RECONSTRUCT_TALL_HEIGHT_MULT,
    _SAME_LINE_CENTER_HEIGHT_RATIO,
    _SAME_LINE_VERTICAL_OVERLAP_RATIO,
    _SEAL_REGION_COLOR,
    _SHORT_FIELD_MAX_COMPACT_LEN,
    _SHORT_FIELD_MAX_DELIMITERS,
    _SHORT_FIELD_MIN_COMPACT_LEN,
    _STANDALONE_AMOUNT_MAX_DIGITS,
    _STANDALONE_AMOUNT_MIN_DIGITS,
    _SUPPLEMENT_HEIGHT_RATIO,
    _SUPPLEMENT_LONGER_TEXT_MARGIN,
    _SUPPLEMENT_SIMILARITY_MIN,
    _SUPPLEMENT_WIDER_RATIO,
    _SUPPLEMENT_WIDTH_RATIO,
    _TABLE_CELL_CONFIDENCE_FACTOR,
    _TABLE_FALLBACK_CONFIDENCE,
    _TABLE_HEURISTIC_DARK_PIXEL_MAX,
    _TABLE_HEURISTIC_HORIZONTAL_DARK_RATIO,
    _TABLE_HEURISTIC_MIN_DIM_PX,
    _TABLE_HEURISTIC_MIN_LINES,
    _TABLE_HEURISTIC_THUMBNAIL_PX,
    _TABLE_HEURISTIC_VERTICAL_DARK_RATIO,
    _TEXTLINE_MIN_HEIGHT_PX,
    _UNION_BLOCK_CONFIDENCE_FACTOR,
    _VISUAL_LINE_JOIN_GAP_HEIGHT_MULT,
    _VISUAL_LINE_JOIN_GAP_MIN_PX,
    AMOUNT_HEADER_LABELS,
    OCR_VISUAL_ENTITY_TYPES,
    TABLE_PRECISION_ENTITY_TYPES,
)
from app.services.vision.ocr_visual_lines import (
    _blocks_same_visual_line,
    _cjk_count,
    _infer_typical_textline_height,
    _is_plain_cjk_or_alnum,
    _join_visual_line_text,
    _should_bridge_short_cjk_prefix,
    _should_join_visual_line_blocks,
    _union_ocr_blocks,
    reconstruct_visual_line_blocks,
)

logger = logging.getLogger(__name__)

__all__ = [
    "AMOUNT_HEADER_LABELS",
    "Any",
    "DEFAULT_HAS_TEXT_TYPE_IDS",
    "DOCUMENT_NUMBER_FIELD_LABEL_TERMS",
    "DOCUMENT_TITLE_SUFFIXES",
    "HTMLParser",
    "Image",
    "ImageOps",
    "OCRTextBlock",
    "OCR_VISUAL_ENTITY_TYPES",
    "OrderedDict",
    "SensitiveRegion",
    "SequenceMatcher",
    "TABLE_PRECISION_ENTITY_TYPES",
    "TYPE_CN_TO_ID",
    "TYPE_ID_TO_CN",
    "VISUAL_ONLY_ENTITY_TYPES",
    "_AMOUNT_FORMAT_ALLOWED_CHARS",
    "_AMOUNT_PAIR_LOOKBACK_CHARS",
    "_AMOUNT_PAIR_MAX_LOWER_TAIL_UNITS",
    "_AMOUNT_PAIR_NO_LOWER_MARKER_UNITS",
    "_AMOUNT_TRAILING_ZEROS_MIN_DIGITS",
    "_AMOUNT_UNIT_SUFFIX_CHARS",
    "_BLANK_PAGE_DARK_PIXEL_MAX",
    "_BLANK_PAGE_DARK_RATIO_MAX",
    "_BLANK_PAGE_INK_PIXEL_MAX",
    "_BLANK_PAGE_INK_RATIO_MAX",
    "_BLANK_PAGE_MIN_HEIGHT_PX",
    "_BLANK_PAGE_MIN_WIDTH_PX",
    "_BLANK_PAGE_THUMBNAIL_PX",
    "_BRIDGE_COMBINED_MAX_LEN",
    "_BRIDGE_LEFT_MAX_LEN",
    "_BRIDGE_LEFT_MIN_CJK",
    "_BRIDGE_LEFT_MIN_LEN",
    "_BRIDGE_PAYLOAD_MAX_CHARS",
    "_BRIDGE_RIGHT_MAX_LEN",
    "_BRIDGE_RIGHT_MIN_CJK",
    "_BRIDGE_RIGHT_MIN_LEN",
    "_CHAR_UNIT_ALNUM",
    "_CHAR_UNIT_CJK",
    "_CHAR_UNIT_MIN_TOTAL",
    "_CHAR_UNIT_OTHER",
    "_CHAR_UNIT_PUNCT",
    "_CHAR_UNIT_SPACE",
    "_COARSE_MULTILINE_HEIGHT_MULT",
    "_COARSE_MULTILINE_MIN_COMPACT_LEN",
    "_DEFAULT_OCR_ITEM_CONFIDENCE",
    "_FIELD_LABEL_COLON_CHARS",
    "_FUZZY_MATCH_BLOCK_LEN_FLOOR",
    "_FUZZY_MATCH_BLOCK_LEN_MULT",
    "_FUZZY_MATCH_CONFIDENCE",
    "_FUZZY_MATCH_MIN_ENTITY_LEN",
    "_FUZZY_MATCH_RATIO",
    "_HAS_ENTITY_TYPE_MAPPING",
    "_HAS_NEGATIVE_HEALTH_TTL_SEC",
    "_HAS_TEXT_NER_INFLIGHT",
    "_HAS_TEXT_NER_INFLIGHT_LOOP",
    "_MERGE_DUPLICATE_IOU",
    "_MERGE_OVERLAP_IOU",
    "_NER_DEFAULT_MIN_LEN",
    "_NER_MIN_LEN_BY_TYPE",
    "_OCR_TEXT_BLOCK_CACHE",
    "_OCR_TEXT_BLOCK_CACHE_LOCK",
    "_OCR_TEXT_BLOCK_INFLIGHT",
    "_OCR_TEXT_BLOCK_INFLIGHT_LOCK",
    "_OcrOutputInflight",
    "_PAREN_CLOSE_CHARS",
    "_PAREN_OPEN_CHARS",
    "_PROPERTY_TITLE_TAIL_LOOKAHEAD_CHARS",
    "_RECONSTRUCT_TALL_ASPECT_MULT",
    "_RECONSTRUCT_TALL_HEIGHT_MULT",
    "_SAME_LINE_CENTER_HEIGHT_RATIO",
    "_SAME_LINE_VERTICAL_OVERLAP_RATIO",
    "_SEAL_REGION_COLOR",
    "_SHORT_FIELD_MAX_COMPACT_LEN",
    "_SHORT_FIELD_MAX_DELIMITERS",
    "_SHORT_FIELD_MIN_COMPACT_LEN",
    "_STANDALONE_AMOUNT_MAX_DIGITS",
    "_STANDALONE_AMOUNT_MIN_DIGITS",
    "_SUPPLEMENT_HEIGHT_RATIO",
    "_SUPPLEMENT_LONGER_TEXT_MARGIN",
    "_SUPPLEMENT_SIMILARITY_MIN",
    "_SUPPLEMENT_WIDER_RATIO",
    "_SUPPLEMENT_WIDTH_RATIO",
    "_TABLE_CELL_CONFIDENCE_FACTOR",
    "_TABLE_FALLBACK_CONFIDENCE",
    "_TABLE_HEURISTIC_DARK_PIXEL_MAX",
    "_TABLE_HEURISTIC_HORIZONTAL_DARK_RATIO",
    "_TABLE_HEURISTIC_MIN_DIM_PX",
    "_TABLE_HEURISTIC_MIN_LINES",
    "_TABLE_HEURISTIC_THUMBNAIL_PX",
    "_TABLE_HEURISTIC_VERTICAL_DARK_RATIO",
    "_TEXTLINE_MIN_HEIGHT_PX",
    "_UNION_BLOCK_CONFIDENCE_FACTOR",
    "_VISUAL_LINE_JOIN_GAP_HEIGHT_MULT",
    "_VISUAL_LINE_JOIN_GAP_MIN_PX",
    "_add_has_text_duration",
    "_amount_digit_count",
    "_amount_digit_signature",
    "_amount_header_column_spans",
    "_amount_value_signature",
    "_amount_values_from_header_spans",
    "_amount_values_from_table_placements",
    "_begin_has_text_ner_inflight",
    "_begin_ocr_output_inflight",
    "_block_search_text",
    "_blocks_same_visual_line",
    "_build_has_text_payload",
    "_build_has_text_type_names",
    "_canonical_image_text_type",
    "_char_visual_units",
    "_char_word_class",
    "_cjk_count",
    "_clone_ocr_output",
    "_clone_sensitive_region",
    "_clone_text_block",
    "_compact_amount_candidate",
    "_compact_text",
    "_copy_has_text_ner_result",
    "_dedupe_ocr_regions",
    "_entity_char_box_x_span",
    "_entity_type_from_block_context",
    "_extend_amount_pair_for_visual_match",
    "_extend_entity_for_visual_match",
    "_filter_blocks_for_has_text",
    "_finish_has_text_ner_inflight",
    "_finish_ocr_output_inflight",
    "_get_cached_has_text_ner",
    "_get_cached_ocr_output",
    "_has_coarse_markup_blocks",
    "_has_coarse_multiline_blocks",
    "_has_recent_negative_health",
    "_has_text_ner_inflight_key",
    "_html_to_plain_text",
    "_image_png_bytes",
    "_infer_typical_textline_height",
    "_is_amount_column_cell",
    "_is_amount_format_text",
    "_is_amount_header_label",
    "_is_coarse_markup_block",
    "_is_document_number_field_label",
    "_is_document_number_format_text",
    "_is_effectively_blank_page",
    "_is_isolated_token_occurrence",
    "_is_low_signal_vision_entity",
    "_is_plain_cjk_or_alnum",
    "_is_same_amount_value_block",
    "_is_standalone_amount_ocr_block",
    "_is_strict_match_entity",
    "_iter_percent_value_tokens",
    "_join_visual_line_text",
    "_looks_like_table",
    "_merge_form_field_document_entities",
    "_merge_ocr_blocks",
    "_merge_table_amount_entities",
    "_narrow_charsless_block_to_lines",
    "_ocr_cache_enabled",
    "_ocr_cache_key",
    "_ocr_items_to_blocks",
    "_ocr_service_cache_identity",
    "_parse_table_placements",
    "_record_has_text_metric",
    "_record_ocr_cache_stage",
    "_record_ocr_stage_duration",
    "_regions_overlap",
    "_run_ocr_service",
    "_run_structure_service_with_visuals",
    "_set_cached_ocr_output",
    "_should_bridge_short_cjk_prefix",
    "_should_join_visual_line_blocks",
    "_should_run_structure_fallback",
    "_split_field_label_value",
    "_union_ocr_blocks",
    "_visual_match_span_for_entity",
    "_visual_match_text_for_entity",
    "_wait_for_ocr_output_inflight",
    "asyncio",
    "expand_table_blocks",
    "extract_table_cells",
    "has_query_labels_for",
    "hashlib",
    "html",
    "io",
    "match_entities_to_ocr",
    "np",
    "prepare_image",
    "recall_form_field_document_numbers",
    "recall_table_amount_entities",
    "reconstruct_visual_line_blocks",
    "run_has_text_analysis",
    "run_paddle_ocr",
    "settings",
    "threading",
    "time",
]
